DROP TABLE IF EXISTS puesto;
DROP TABLE IF EXISTS departamento;
DROP TABLE IF EXISTS persona;

CREATE TABLE Puesto(
	ID INT(20) AUTO_INCREMENT PRIMARY KEY,
    Nom_Pst VARCHAR(255)
);

CREATE TABLE Departamento(
	ID INT(20) AUTO_INCREMENT PRIMARY KEY,
    Nom_Dpmt VARCHAR(100),
    ID_Pst INT(20),
    FOREIGN KEY(ID_Pst) REFERENCES Puesto(ID)
);

CREATE TABLE Persona(
	ID INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100),
    Email VARCHAR(255),
    Telefono INT (9),
    ID_Pst INT(20),
    ID_Dpmt INT(20),
    FOREIGN KEY(ID_Pst) REFERENCES Puesto(ID),
    FOREIGN KEY(ID_Dpmt) REFERENCES Departamento(ID)
);